// gtd-vue-app/src/components/ProjectItem.vue
<script setup>
import { ChevronDown, ChevronRight, Edit2, Check, X, Trash2 } from 'lucide-vue-next';
import { defineProps, defineEmits, ref, nextTick } from 'vue';

const props = defineProps({
  node: { type: Object, required: true },
  expanded: { type: Boolean, default: false },
  active: { type: Boolean, default: false },
  icon: { type: [Object, Function], default: null }, 
  tip: { type: String, default: '' }
});

const emit = defineEmits(['toggle', 'select', 'rename', 'delete', 'drop-task']);

const hasChildren = props.node.children.length > 0;
const isEditing = ref(false);
const editName = ref('');
const inputRef = ref(null);
const isDragOver = ref(false);

const onDragOver = (e) => {
  e.preventDefault();
  e.dataTransfer.dropEffect = 'move';
  isDragOver.value = true;
};

const onDrop = (e) => {
  isDragOver.value = false;
  try {
    const taskData = JSON.parse(e.dataTransfer.getData('task'));
    emit('drop-task', taskData.lineIndex, props.node.path);
  } catch (err) {
    console.error('Drop error:', err);
  }
};

const startRenaming = (e) => {
  e.stopPropagation();
  editName.value = props.node.name;
  isEditing.value = true;
  nextTick(() => inputRef.value?.focus());
};

const saveRename = () => {
  if (editName.value.trim() && editName.value !== props.node.name) {
    emit('rename', props.node.path, editName.value.trim());
  }
  isEditing.value = false;
};

const cancelRename = () => {
  isEditing.value = false;
};
</script>

<template>
  <div class="group/proj relative">
    <div 
      class="flex items-center gap-2 px-3 py-2.5 rounded-2xl cursor-pointer transition-all border-2 border-transparent"
      :class="[
        active ? 'bg-blue-50 dark:bg-blue-900/20 text-blue-700 dark:text-blue-400' : 'text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-700/50',
        isDragOver ? 'border-blue-400 bg-blue-50 dark:bg-blue-900/30' : ''
      ]"
      @click="emit('select', node)"
      @dragover="onDragOver"
      @dragleave="isDragOver = false"
      @drop.stop="onDrop"
      :title="tip"
    >
      <button 
        class="w-5 h-5 flex items-center justify-center text-slate-400 dark:text-slate-500 hover:text-blue-500 transition-colors" 
        @click.stop="emit('toggle', node.path)"
      >
        <template v-if="hasChildren">
          <ChevronDown v-if="expanded" :size="16" class="stroke-[3]"/>
          <ChevronRight v-else :size="16" class="stroke-[3]"/>
        </template>
        <template v-else>
          <component :is="icon" v-if="icon" :size="16" class="text-slate-400 dark:text-slate-500"/>
          <div v-else class="w-4" />
        </template>
      </button>
      
      <div v-if="isEditing" class="flex-1 flex items-center gap-1" @click.stop>
        <input 
          ref="inputRef"
          v-model="editName" 
          class="flex-1 bg-white dark:bg-slate-900 border border-blue-300 dark:border-blue-800 rounded px-1.5 py-0.5 text-sm font-bold outline-none dark:text-slate-200"
          @keydown.enter="saveRename"
          @keydown.esc="cancelRename"
        />
        <button @click="saveRename" class="text-emerald-500 hover:bg-emerald-50 dark:hover:bg-emerald-900/20 p-1 rounded transition-colors"><Check :size="14"/></button>
      </div>
      <template v-else>
        <span class="text-sm truncate flex-1 tracking-tight" :class="active ? 'font-black' : 'font-bold'">
          {{ node.displayName || node.name }}
        </span>
        
        <button 
          @click="startRenaming"
          class="opacity-0 group-hover/proj:opacity-100 p-1 text-slate-300 dark:text-slate-600 hover:text-blue-500 rounded transition-all"
          title="重命名项目"
        >
          <Edit2 :size="12"/>
        </button>

        <button 
          @click.stop="emit('delete', node.path)"
          class="opacity-0 group-hover/proj:opacity-100 p-1 text-slate-300 dark:text-slate-600 hover:text-red-500 rounded transition-all"
          title="删除项目"
        >
          <Trash2 :size="12"/>
        </button>

        <span class="text-[10px] font-bold text-slate-400 dark:text-slate-500 px-1">
          {{ node.incompleteCount || 0 }}
        </span>
      </template>
    </div>
    
    <!-- Restrict to 2 levels (level 1 nodes can show children, level 2 nodes cannot) -->
    <div v-if="expanded && node.level < 2" class="ml-5 border-l-2 border-slate-50 dark:border-slate-700 pl-1 mt-1">
      <ProjectItem 
        v-for="child in node.children" 
        :key="child.path"
        :node="child"
        :expanded="expanded" 
        :active="active"
        @select="(n) => emit('select', n)"
        @toggle="(p) => emit('toggle', p)"
        @rename="(p, n) => emit('rename', p, n)"
        @delete="(p) => emit('delete', p)"
        @drop-task="(l, p) => emit('drop-task', l, p)"
        :tip="tip"
        :icon="icon"
      />
    </div>
  </div>
</template>

// gtd-react-app/src/components/ProjectItem.tsx
import React, { useState, useRef, useEffect } from 'react';
import { ChevronDown, ChevronRight, Edit2, Check, Trash2, Hash } from 'lucide-react';
import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';
import { ProjectNode } from '../types/gtd';

const cn = (...inputs: ClassValue[]) => twMerge(clsx(inputs));

interface ProjectItemProps {
  node: ProjectNode;
  expanded: boolean;
  active: boolean;
  icon: React.ElementType;
  onToggle: (path: string) => void;
  onSelect: (node: ProjectNode) => void;
  onRename: (path: string, newName: string) => void;
  onDelete: (path: string) => void;
  onDropTask: (idx: number, targetPath: string) => void;
}

const ProjectItem: React.FC<ProjectItemProps> = ({ 
  node, expanded, active, icon: Icon, 
  onToggle, onSelect, onRename, onDelete, onDropTask 
}) => {
  const [isEditing, setIsEditing] = useState(false);
  const [editName, setEditName] = useState(node.name);
  const [isDragOver, setIsDragOver] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);

  const hasChildren = node.children && node.children.length > 0;

  useEffect(() => {
    if (isEditing) inputRef.current?.focus();
  }, [isEditing]);

  const handleSave = (e?: React.MouseEvent) => {
    e?.stopPropagation();
    if (editName.trim() && editName !== node.name) {
      onRename(node.path, editName.trim());
    }
    setIsEditing(false);
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragOver(false);
    try {
      const taskData = JSON.parse(e.dataTransfer.getData('task'));
      onDropTask(taskData.lineIndex, node.path);
    } catch (err) {
      console.error('Drop error:', err);
    }
  };

  return (
    <div className="group/proj relative">
      <div 
        className={cn(
          "flex items-center gap-3 px-3 py-2 rounded-2xl cursor-pointer transition-all duration-300 border border-transparent mb-0.5",
          active 
            ? "bg-blue-600/10 dark:bg-blue-500/10 text-blue-600 dark:text-blue-400 font-bold border-blue-500/20" 
            : "text-slate-500 dark:text-slate-400 hover:bg-white dark:hover:bg-slate-800/50 hover:shadow-sm",
          isDragOver && "border-blue-500 bg-blue-50 dark:bg-blue-900/30 ring-4 ring-blue-500/10"
        )}
        onClick={() => onSelect(node)}
        onDragOver={(e) => { e.preventDefault(); setIsDragOver(true); }}
        onDragLeave={() => setIsDragOver(false)}
        onDrop={handleDrop}
      >
        <button 
          className="w-5 h-5 flex items-center justify-center text-slate-400 hover:text-blue-500 transition-colors"
          onClick={(e) => { e.stopPropagation(); onToggle(node.path); }}
        >
          {hasChildren ? (
            expanded ? <ChevronDown size={14} strokeWidth={3} /> : <ChevronRight size={14} strokeWidth={3} />
          ) : (
            <Icon size={14} className={cn(active ? "text-blue-500" : "text-slate-400")} />
          )}
        </button>

        {isEditing ? (
          <div className="flex-1 flex items-center gap-1.5" onClick={e => e.stopPropagation()}>
            <input 
              ref={inputRef}
              value={editName}
              onChange={e => setEditName(e.target.value)}
              onKeyDown={e => { if (e.key === 'Enter') handleSave(); if (e.key === 'Escape') setIsEditing(false); }}
              className="flex-1 bg-white dark:bg-slate-900 border border-blue-500/30 rounded-lg px-2 py-0.5 text-xs font-bold outline-none ring-2 ring-blue-500/10"
            />
          </div>
        ) : (
          <>
            <span className="text-[13px] truncate flex-1 tracking-tight font-medium">
              {node.displayName || node.name}
            </span>
            
            <div className="flex items-center gap-1 opacity-0 group-hover/proj:opacity-100 transition-all duration-300">
              <button 
                onClick={(e) => { e.stopPropagation(); setEditName(node.name); setIsEditing(true); }}
                className="p-1 text-slate-300 hover:text-blue-500 hover:bg-blue-50 dark:hover:bg-blue-900/30 rounded-md transition-colors"
              >
                <Edit2 size={11}/>
              </button>
              <button 
                onClick={(e) => { e.stopPropagation(); onDelete(node.path); }}
                className="p-1 text-slate-300 hover:text-rose-500 hover:bg-rose-50 dark:hover:bg-rose-900/30 rounded-md transition-colors"
              >
                <Trash2 size={11}/>
              </button>
            </div>

            {node.incompleteCount > 0 && (
              <span className={cn(
                "text-[10px] font-black px-1.5 py-0.5 rounded-full min-w-[20px] text-center",
                active ? "bg-blue-500 text-white" : "bg-slate-100 dark:bg-slate-800 text-slate-400"
              )}>
                {node.incompleteCount}
              </span>
            )}
          </>
        )}
      </div>

      {expanded && hasChildren && (
        <div className="ml-5 border-l border-slate-200/50 dark:border-slate-800/50 pl-2 mt-1 space-y-0.5">
          {node.children.map(child => (
            <ProjectItem 
              key={child.path}
              node={child}
              expanded={expanded}
              active={active && child.path === node.path} // simplified for now
              icon={Hash}
              onToggle={onToggle}
              onSelect={onSelect}
              onRename={onRename}
              onDelete={onDelete}
              onDropTask={onDropTask}
            />
          ))}
        </div>
      )}
    </div>
  );
};

export default ProjectItem;
